# Generated by Django 4.2.4 on 2023-10-12 18:09

import BlazeAdministration.customValidator
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=7, validators=[BlazeAdministration.customValidator.validate_studentUsername])),
                ('batch', models.CharField(max_length=2, validators=[BlazeAdministration.customValidator.validate_studentBatch])),
                ('nuid', models.CharField(max_length=4, unique=True, validators=[BlazeAdministration.customValidator.validate_studentNUID])),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('SE', 'Software Engineering'), ('AI', 'Artificial Intelligence'), ('CYS', 'Cyber Security'), ('EE', 'Electrical Engineering')], max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[BlazeAdministration.customValidator.validate_studentEmail])),
                ('profile_picture', models.ImageField(blank=True, default='profile_pics/Default_Profile_Picture.png', null=True, upload_to='profile_pics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), BlazeAdministration.customValidator.validate_profilePicture_size])),
                ('groups', models.ManyToManyField(blank=True, related_name='student_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='student_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
