# Generated by Django 4.2.4 on 2023-11-15 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Title', max_length=200)),
                ('description', models.CharField(default='No Description', max_length=1500)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Academics', 'Academics'), ('Thoughts', 'Thoughts'), ('Social Issues', 'Social Issues'), ('Events and Meetups', 'Events and Meetups'), ('Personal Development', 'Personal Development'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=50)),
                ('poster', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Enter the content of your answer/reply (up to 500 characters).', max_length=500)),
                ('date', models.DateField(auto_now=True)),
                ('poster', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
