# Generated by Django 4.2.4 on 2023-10-14 17:50

import BlazeAdministration.customValidator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='not_set', max_length=2, validators=[BlazeAdministration.customValidator.validate_studentBatch]),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('SE', 'Software Engineering'), ('AI', 'Artificial Intelligence'), ('CYS', 'Cyber Security'), ('EE', 'Electrical Engineering')], default='not_set', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='nuid',
            field=models.CharField(default='not_set', max_length=4, unique=True, validators=[BlazeAdministration.customValidator.validate_studentNUID]),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to=settings.AUTH_USER_MODEL),
        ),
    ]
