# Generated by Django 4.2.4 on 2023-10-14 17:51

import BlazeAdministration.customValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0003_student_batch_student_department_student_nuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=7, null=True, validators=[BlazeAdministration.customValidator.validate_studentUsername]),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(max_length=2, null=True, validators=[BlazeAdministration.customValidator.validate_studentBatch]),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('SE', 'Software Engineering'), ('AI', 'Artificial Intelligence'), ('CYS', 'Cyber Security'), ('EE', 'Electrical Engineering')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nuid',
            field=models.CharField(max_length=4, null=True, unique=True, validators=[BlazeAdministration.customValidator.validate_studentNUID]),
        ),
    ]
