# Generated by Django 4.2.4 on 2023-11-15 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0006_remove_comment_post_comment_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='category',
            new_name='object_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(default='No Content', max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_type',
            field=models.CharField(choices=[('Post', 'Post'), ('Event', 'Event'), ('Forum', 'Forum')], default='Post', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
