# Generated by Django 4.2.4 on 2023-11-16 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0009_rename_date_post_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='timestamp',
        ),
    ]
