# Generated by Django 4.2.4 on 2023-10-16 18:06

import BlazeAdministration.customValidator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0009_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/Default_Profile_Picture.png', null=True, upload_to='profile_pics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), BlazeAdministration.customValidator.validate_profilePicture_size]),
        ),
    ]
