# Generated by Django 4.2.4 on 2023-10-29 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0011_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('EE', 'Electrical Engineering')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocietyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyHead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HeadOfSociety', to='BlazeApp.faculty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='societyPage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
