# Generated by Django 4.2.4 on 2023-10-29 17:06

import BlazeAdministration.customValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0012_faculty_societypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nuid',
            field=models.CharField(max_length=4, null=True, validators=[BlazeAdministration.customValidator.validate_studentNUID]),
        ),
    ]
