# Generated by Django 4.2.4 on 2023-11-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0012_rename_date_answer_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date',
            new_name='timestamp',
        ),
    ]
