# Generated by Django 4.2.4 on 2023-11-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0014_remove_student_profile_picture_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='major',
        ),
    ]
