# Generated by Django 4.2.4 on 2023-11-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0015_rename_date_share_timestamp_alter_event_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_type',
            field=models.CharField(choices=[('post', 'Post'), ('event', 'Event')], default='Post', max_length=10),
        ),
    ]
