# Generated by Django 4.2.4 on 2023-11-14 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0015_rename_department_student_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyHead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headOfSociety', to='BlazeApp.faculty')),
                ('president', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president', to='BlazeApp.student')),
                ('treasurer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasurer', to='BlazeApp.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='society', to=settings.AUTH_USER_MODEL)),
                ('vicePresident', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vicePresident', to='BlazeApp.student')),
            ],
        ),
        migrations.DeleteModel(
            name='SocietyPage',
        ),
    ]
