# Generated by Django 4.2.4 on 2023-11-16 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0016_alter_comment_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved',
            field=models.ManyToManyField(related_name='saved_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
