# Generated by Django 4.2.4 on 2023-11-14 16:56

import BlazeAdministration.customValidator
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0016_society_delete_societypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='facultyHead',
        ),
        migrations.RemoveField(
            model_name='society',
            name='vicePresident',
        ),
        migrations.AddField(
            model_name='society',
            name='faculty_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_head', to='BlazeApp.faculty'),
        ),
        migrations.AddField(
            model_name='society',
            name='vice_president',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_president', to='BlazeApp.student'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_picture', models.ImageField(blank=True, help_text='Upload an image for the post (optional).', null=True, upload_to='posts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), BlazeAdministration.customValidator.validate_profilePicture_size])),
                ('post_content', models.CharField(help_text='Enter the content of your post (up to 1500 characters).', max_length=1500)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
