# Generated by Django 4.2.4 on 2023-11-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0018_alter_event_likes_alter_post_likes_alter_post_saved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='timestam',
        ),
    ]
