# Generated by Django 4.2.4 on 2023-11-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0020_remove_comment_content_type_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.CharField(choices=[('post', 'Post'), ('Forum', 'Forum'), ('Event', 'Event')], max_length=10),
        ),
    ]
