# Generated by Django 4.2.4 on 2023-11-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0021_post_original_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.AddField(
            model_name='answer',
            name='replies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_of_this_answer', to='BlazeApp.answer'),
        ),
    ]
