# Generated by Django 4.2.4 on 2023-11-18 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0022_delete_reply_answer_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='replies',
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Enter the content of your answer/reply (up to 500 characters).', max_length=500)),
                ('timestamp', models.DateField(auto_now=True)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='BlazeApp.answer')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
            },
        ),
    ]
