# Generated by Django 4.2.4 on 2023-11-18 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0023_remove_answer_replies_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='replies_of_this_answer', to='BlazeApp.answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='BlazeApp.question'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
