# Generated by Django 4.2.4 on 2023-12-02 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0026_faculty_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
