# Generated by Django 4.2.4 on 2023-12-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0027_question_saved_question_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='saved',
        ),
    ]
