# Generated by Django 4.2.4 on 2023-12-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0028_remove_question_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
