# Generated by Django 4.2.4 on 2023-12-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlazeApp', '0030_alter_answer_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['timestamp'], 'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('EE', 'Electrical Engineering')], default='Computer Science', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='object_type',
            field=models.CharField(choices=[('post', 'Post'), ('event', 'Event'), ('question', 'Question')], default='post', max_length=10),
        ),
    ]
